### ISSUE TITLE
Error in deparse(expr) : object 'expr' not found

### ISSUE THREAD

**Issue by HJ234** [jokergoo/bsub#34]
Hi, Thank you for the great program. 
I'm trying to use a for loop to bsub several jobs at once but I keep getting an error from deparse. Would you know why this happens? 
It seems like it only happens when I try to set variables="chr"

```
>library(bsub)
>library(ssh)
>library(GetoptLong)
>bsub_opt$bsub_template = function(name, hours, memory, cores, output, ...) {glue::glue("bsub -J '{name}' -W '{hours}:00' -n {cores} -R'select[mem>{memory}] rusage[mem={memory}]' -M{memory} -o >'{output}'")}
> for (chr in 1:22){
+   bsub_chunk(packages="EPIC", memory = 10000, hours = 10, cores = 4, variables="chr",{ 
+     print(chr)
+   })
+ }
Error in deparse(expr) : object 'expr' not found
```
By the way, this is the sanger server

**Comment by jokergoo** [comment]
What is the output from `traceback()`? I might have misspelled some variables.

**Comment by HJ234** [comment]
Thank you for the quick reply. Unfortunately, the traceback seems to give no answers.

```
> traceback()
2: deparse(expr)
1: bsub_chunk(packages = "EPIC", memory = 10000, hours = 10, cores = 4, 
       variables = "chr", {
           print(chr)
       })
```

**Comment by jokergoo** [comment]
I have fixed this problem. Can you try the newest version from GitHub?
